### ISSUE TITLE
Example JSON is not valid

### ISSUE THREAD

**Issue by jamesaoverton** [mapping-commons/SSSOM#1]
The code examples in `SSSOM.md` are not valid JSON: no trailing commas, smart quotes.

Is there an implicit JSON-LD context? Making that explicit could double as an indication of which version of this standard was used.

I'm confused by `"date":	“2020-09-2020"`. It might be good to enforce a date format.

Although it's a bit of a pain, I suggest writing a script that executes/tests/validates the documentation against your tools, to ensure that the examples are always right.

**Comment by matentzn** [comment]
Date question is now discussed in #67 

The metadata in the SSSOM header files is now YAML, and I checked that at least the references in the documentations are valid.
