### ISSUE TITLE
Consider rdfstar serialization

### ISSUE THREAD

**Issue by cmungall** [mapping-commons/sssom#104]
RDFStar seems attractive as a form of serialization:

```turtle
<< subj pred obk  >> :confidence "0.5"^^xsd:float, match_type "Lexial", ....
```

However,  note that rdfstar does not follow rdf reification in directly allowing multiple statements of the same triple. To ensure roundtripping I think it would be necessary to do:

```turtle
<< << subj pred obk  >>  :confidence "0.5"^^xsd:float, match_type "Lexial", ....>>
```

see also
https://github.com/cmungall/owlstar/issues/14

Note: it is perfectly acceptable to close this with a won't-do tag

**Comment by matentzn** [comment]
Are we positive this is the case in RDF-Star.. I still cannot believe it.

**Comment by cmungall** [comment]
yes https://twitter.com/chrismungall/status/1463976008667709443
