### ISSUE TITLE
[New metadata element]: predicate_modifier

### ISSUE THREAD

**Issue by hrshdhgd** [mapping-commons/sssom#107]
**Element id (e.g. creator_id, mapping_tool_version):**

```
predicate_modifier
```

**Value data type (e.g. URI, URL, text, xsd:boolean):**

I'm not sure ... 
```
xsd:string
```

**Description**
This is a modifier to predicates to express either negation (`NOT`) , inverse (`INVERSE`) or other relations (e.g. `INDIRECT`). This request is in response to our development in SSSOM-PY.

cc: @matentzn , @cmungall .

**Comment by cthoyt** [comment]
See #99

**Comment by matentzn** [comment]
Fixed in #99 thanks both
