### ISSUE TITLE
Unbreak autopushing docs

### ISSUE THREAD

**Issue by matentzn** [mapping-commons/sssom#116]
https://github.com/mapping-commons/sssom/runs/4407903105?check_suite_focus=true

For some reason build.yml does not work anymore - @hrshdhgd do you mind looking at that for a moment?

**Comment by matentzn** [comment]
Maybe while you are at it, combine with https://github.com/mapping-commons/sssom/issues/115?

**Comment by hrshdhgd** [comment]
The build.yml works as expected now and highlighted the issues along the way.

1. The `Pipfile` and the `Pipfile.lock` are currently present in the `make-venv` directory. 
    - Because of this, pipenv cannot see these two files when running within GitHub actions (locally as well for me) and hence creating new files (with none of the necessary packages listed). Thus the test was failing at `Module not found: linkml_runtime`
    - **Solution**: I copied the two files to the home directory and moved past this error to the next one
    - **Question**: Should we just move the 2 files to the home directory as opposed to having them within 'make-venv' directory?

2. `ImportError: cannot import name 'Person' from 'sssom.sssom' (/home/runner/work/sssom/sssom/sssom/sssom.py)`
    - This error arises from [this line](https://github.com/mapping-commons/sssom/blob/b48d18cef70130628639e74bea42032a435ae7ce/tests/test_input_against_model.py#L6). There is no definition of the `Person` class in the project. How do I proceed?

cc @matentzn , @cmungall

**Comment by matentzn** [comment]
@hrshdhgd has fixed this.
