### ISSUE TITLE
sssom_metadata.tsv is confusing to the uninitiated

### ISSUE THREAD

**Issue by cmungall** [mapping-commons/sssom#12]
The actual format of SSSOM is kinda hard to grok in the docs

You have to go to
https://github.com/OBOFoundry/SSSOM/blob/master/SSSOM.md#tsv

which is very texty

In the text is buried a link to

https://github.com/OBOFoundry/SSSOM/blob/master/sssom_metadata.tsv

Which is hard to interpret

Which is a bit confusing. It looks like the first column in SSSOM is 'ID'. It took me a whole to realize this was a robot template

Also, the sssom: prefixes are confusing, they aren't actually meant to be used in the header are they?

I suggest a simple derived table that looks more like the original gdoc

also I use this hacky script to make gh tables from tsvs, may be helpful here:

```
#!/usr/bin/perl

my $n=0;
my $len;
my $hlen;
while(<>) {
    chomp;
    if ($n==0 && m@^\#@) {
        s@^\#@@;
    }
    my (@vals) = split(/\t/,$_);
    @vals = map {s@\|@, @g; $_} @vals;
    if (!$hlen) {
        $hlen = scalar(@vals);
    }
    while (scalar(@vals) < $hlen) {
        push(@vals, '');
    }
    print '|'.join('|',@vals)."|\n";
    $nulen = scalar(@vals);
    if ($n > 0) {
        if ($len ne $nulen) {
            print STDERR "MISMATCH: $len != $nulen\n";
        }
    }
    $len = $nulen;
    if ($n ==0) {
        @vals = map {"---"} @vals;
        print '|'.join('|',@vals)."|\n";
    }
    $n++;
}
```

**Comment by matentzn** [comment]
I have added the table back:
https://github.com/OBOFoundry/SSSOM/blob/master/SSSOM.md#meta

I will keep the two in sync manually until SSSOM stabilized (its no biggie).

**Comment by matentzn** [comment]
Does not exist anymore, replaced by https://github.com/mapping-commons/semantic-mapping-vocabulary
