### ISSUE TITLE
More information on match types

### ISSUE THREAD

**Issue by cthoyt** [mapping-commons/sssom#14]
Besides lexical mappings, what kinds of match types do you envision people asserting? I read through the SSSOM controlled vocabulary and didn't see anything about lexical mapping or other types there. It would be good to give examples of other types, and also specify how this column should be used

**Comment by matentzn** [comment]
The match type [vocabulary](https://github.com/OBOFoundry/SSSOM/blob/master/sssom_vocab.tsv) is in a provisional state, reflecting the most important categories we needed to distinguish for our use cases:

| Match Type | Label | Definition |
| -- | -- | -- |
| SSSOMC:Lexical | Lexical match | Match is based on any lexical information provided by the subject and the object. | 
| SSSOMC:Logical | Logical match | Match is based on the logical definition of the subject and the object (logical equivalence), as determined by a semantic reasoner. | 
| SSSOMC:HumanCurated | Human Curated match | Match is based on human curation. | 
| SSSOMC:Complex | Complex match | Match is based on a combination of match types. It is recommended that the tool used for the match is provided, and more information given in a comment. |

In an earlier draft, we considered many more distinctions (like a more fine-grained typology around lexical matches that provide detail around the fields that matched etc), but most of these have hence been pushed into other metadata fields.

Hope this makes sense!

**Comment by cthoyt** [comment]
Thanks @matentzn this is very helpful (sorry I ready this before and didn't comment)

Maybe you'd consider adding it to the README?

**Comment by matentzn** [comment]
Sure, I will make sure I do that during the next revision. Thanks a ton :)

**Comment by matentzn** [comment]
This is now being taken care of here: https://github.com/mapping-commons/semantic-mapping-vocabulary
