### ISSUE TITLE
Move match_type from enum to entity format

### ISSUE THREAD

**Issue by matentzn** [mapping-commons/sssom#141]
Previously, the match_type element was a controlled vocabulary managed as a relatively static enum in LinkML. Given the many ways in which we may want to extend match_types, we now think it is better to define an external vocabulary for this.

This issue serves as a warning to that end: when the proposal is approved by the [core team](https://github.com/orgs/mapping-commons/teams/sssom-core), elements like `HumanCurated`, `Lexical` etc will have to be prefixed like:

sssom:HumanCurated, sssom:Lexical.

**Comment by matentzn** [comment]
This has been done in #164

**Comment by saubin78** [comment]
Hi! will this be available in the 1.0 version of SSSOM? 
When do you expect to publish the 1.0 version?

**Comment by matentzn** [comment]
It will be! It is already on the master branch.. I think you can expect this to be in SSSOM 1.0 as is.
