### ISSUE TITLE
Tear apart the `match_term_type` into to new elements

### ISSUE THREAD

**Issue by matentzn** [mapping-commons/sssom#143]
Currently, we have the `match_term_type`, to indicate wether a match is between classes, properties etc.

- TermMatch: A match between two terms
- ConceptMatch: A match between two SKOS concepts
- ClassMatch: A match between two OWL/RDFS classes
- ObjectPropertyMatch: A match between two OWL object properties
- IndividualMatch: A match between two OWL Individuals
- DataPropertyMatch: A match between two OWL object properties

This is a bit limited because we may have to map between different kinds of elements. Before finalising version 1, we would like to propose to remove this field in favour of a more fine grained approach that allows to provide typing for both the subject and the subject, like:

- `subject_type` (owl:Class, rdf:Resource, skos:Concept etc etc)
- `object_type`
- `predicate_type` (owl:AnnotationProperty)

This gives us a range of advantages:
1. We can use the semantic web standard vocabularies for entity types and do not have to define our own
2. We can use the typing information in tools which is very useful for example when generating OWL mappings
3. We avoid combinatorial explosions of match_types (ObjectPropertyToAnnotationPropertyMatch, ClassToDatabaseEntityMatch)

@ernestojimenezruiz since you were the one proposing this element originally, can you provide use with some feedback on this proposal?

**Comment by ernestojimenezruiz** [comment]
Hi Nico

Apologies for the slow response. I'm in the middle of the teaching term.

I think adding a type to both the subject and object will be a good option. This way we can also allow for more general mappings.

match_term_type was handy for retrieval purposes, but adding the type of the subject and object will lead to the same retrieval options and beyond (i.e. classMatch => both subject and object are owl:Class). The predicate can also be meaningful in this regard, that is, owl:EquivalentClass is assumed to be used among owl:Classes. I guess when mixing types in the matching, one should avoid owl equivalence/subsumption pedicates.

Ernesto

PS: there is a typo here: DataPropertyMatch: A match between two OWL **data** properties.

**Comment by matentzn** [comment]
Thank you very much @ernestojimenezruiz! This is great!
