### ISSUE TITLE
New mapping justification: cross-walk

### ISSUE THREAD

**Issue by matentzn** [mapping-commons/sssom#152]
We need a new justification for a mapping which is a crosswalk across mappings. Rather than storing as metadata the exact walk, I suggest we store the record the mapping sets (version IRI) that are used to support the walk. Furthermore, we indicate the number of hops:

| subject_id | predicate_id | object_id | mapping_justification | cross_walk_hops | mapping_source |
| ---- | ---- | ---- | ---- | ---- | ---- |
| HP:001 | skos:exactMatch | MP:001 | sssom:CrossWalk | 3 | mondo_mapping_set:1, hpo_mapping_set:2 |

**Comment by graybeal** [comment]
Please define it. I have seen crosswalk used in multiple ways.

**Comment by matentzn** [comment]
Sorry, I should have been more precise, thank you for checking in. The SEMAF people discuss this a lot here: https://zenodo.org/record/4651421 (without providing a definition), but a cross-walk is essentially an inference process that applies "chaining rules" (see https://github.com/mapping-commons/sssom/issues/79 by @cthoyt) on a set of mappings. Maybe: A cross-walk is "path through the mapping graph in accordance to chaining rules".

**Comment by jonquet** [comment]
I would not use the word "crosswalk" for a justification. 
I dont' think crosswalk is the term for the chain described in #79 
In fact, crosswalk is a fuzzy term used by certains communities (more in the word of metadata than vocabularies/ontologies) to say "mapping". Typically, folks will talk about "crosswalks between metadata standards" 
This was also my impression of the meaning of the word in the SEMAF doc.

**Comment by matentzn** [comment]
Interesting! Maybe you are right ([wikipedia](https://en.wikipedia.org/wiki/Schema_crosswalk), I am also not 100% sure about that term. You understand what I want to say, how would you  "name" it? In OxO they are called "hops". Any other idea? One option is to say its "logical", like an inference as specified by the predicate semantics, but I want something more specific as this is essential metadata for many of our use cases. `Multi-hopMatching`?

**Comment by graybeal** [comment]
It seems to me it's an 'inference chain', an expression I've seen many times before and seems clear.

**Comment by matentzn** [comment]
Good suggestion @graybeal lets see if there are any others, else I will use that!

**Comment by matentzn** [comment]
This discussion has now moved here: https://github.com/mapping-commons/semantic-mapping-vocabulary

The current proposal is `semapv:MappingChaining`, please open an issue on the above if you want to continue the discussion.
