### ISSUE TITLE
Contribution to SSSOM

### ISSUE THREAD

**Issue by iandharrow** [mapping-commons/sssom#16]
Hi Nico

I would like to contribute to building the new SSSOM format which I have been discussing with Thomas Liener. You can reach me at ianharrowconsulting(at)gmail(dot)com to this follow-up. You will find me on LinkedIn and the Pistoia Alliance website (Manager for Ontology Mapping and FAIR Implementation projects).

Cheers, Ian

**Comment by cmungall** [comment]
I will mention SSSOM in my Mondo talk for Pistoia

**Comment by linikujp** [comment]
When will it be?

**Comment by cmungall** [comment]
This thursdya

**Comment by matentzn** [comment]
Thanks for all of your help @iandharrow!

**Comment by matentzn** [comment]
I have invited you to the core editorial team as well https://github.com/orgs/mapping-commons/teams/sssom-core
