### ISSUE TITLE
Add unit tests for sssom data model

### ISSUE THREAD

**Issue by matentzn** [mapping-commons/sssom#165]
This was started here: https://github.com/mapping-commons/sssom/pull/124

We want at least two comprehensive example sssom file with:

- Parsing with newly generated `sssom.py`  dataclasses
- running basic linkml validation

**Comment by cmungall** [comment]
the standard we are approaching for linkml-centric projects is an examples and counter-examples folder, then run a single command to ensure the former all pass, and the latter all fail (with expected violations); and also the examples incorporated into the docs
