### ISSUE TITLE
[New metadata element]: `curation_rule`

### ISSUE THREAD

**Issue by matentzn** [mapping-commons/sssom#166]
**Element id (e.g. creator_id, mapping_tool_version):**
(Must be lower case and contain only letters and underscores.)

```
curation_rule
```

**Value data type (e.g. URI, URL, text, xsd:boolean):**

```
EntityReference (URI/CURIE)
```

**Description**

See #150 for wider context. 

A curation rule is a (potentially) complex condition executed by a human curator that led to the establishment of a mapping. Curation rules often involve complex domain-specific considerations, which are hard to capture in an automated fashion. 

**Constraints**

- Should only be recorded in conjunction with `mapping_justification: HumanCurated`.
- Should be recorded with a term from a controlled vocabulary

**Examples**

https://github.com/mapping-commons/disease-mappings/issues/16

**Comment by saubin78** [comment]
Has this element been implemented? Will it be available in 1.0?

**Comment by matentzn** [comment]
Unfortunately this was not planned for 1.0, but 1.1. Can you outline why you would need it more quickly? What use case are you thinking of using it for?

**Comment by saubin78** [comment]
Hi! No hurry. 
We'll discuss this point next week around D2KAB project's use cases and come back to you with further elements. We'll see in particular if values from a controlled vocabulary would fit, not quite sure...

**Comment by matentzn** [comment]
We have been curating some examples for these, but I don't think the vocabulary should be standardised - there is a wide space of curation rules, and many can get very specific for any given ontology. Here we are discussing some very concrete examples: https://github.com/mapping-commons/disease-mappings/issues/16

**Comment by saubin78** [comment]
What is the status of curation_rule in the current SSSOM specification? As far as I can see, it has not been introduced in the model. Is there any plan for this?

**Comment by saubin78** [comment]
I am not 100% convinced by the statement "Should only be recorded in conjunction with mapping_justification: HumanCurated."
Wouldn't rules be relevant with e.g. semapv:BackgroundKnowledgeBasedMatching or semapv:LogicalReasoning?

**Comment by saubin78** [comment]
Hi,
our curation rules are short texts. For now, they look like this :
```
Rule 3 is about abiotic stress and tolerance of the plant to metal toxicity.
metal + toxicity (WTO) <-> metal + tolerance  (CO321)

Example: 
Aluminium toxicity (WTO:0000450) <-> Aluminium tolerance (CO_321:0000079)
```
or this one, that has subrules :

```
Rule 1 is about biotic stresses. WTO defines general trait classes of response to pests and disease for WTO. CO_321 defines traits about the observable degree of affection. The observation may be done on the whole plant, or a subpart of it. 
We consider that the user of the information retrieval function, given a pathogen or a disease, would like to retrieve all data, independently of the way the affection is observed. As a consequence, the retrieval terms score, incidence, severity, response, index, coefficent, progress curve and resistance are considered as similar.

1.1 Score
resistance + ’name of disease’ (WTO) <-> ’name of disease’ + score (CO321)

Example from CO_321 : Septoria score on leaf  (CO_321:1010036)
And from WTO : resistance to Septoria Leaf Blotch (WTO:0000554)

The score is a direct measure on the plant. It is usually a discret number between 0 an 6 or 10.
```

**Comment by saubin78** [comment]
In short term, I'd like to use the "curation_rule" element and find the best way to publish the rules. For now I see two possibilities :

1. Record the rules in a document that would go with the mapping dataset and reference the rules in the SSSOM representation using the codes (eg 1.1 or 2 in my examples above)
2. Publish each rule as a RDF resource (= nanopublication?) and reference it with its URI in the SSSOM representation of our mappings. But what would be the type for these resources? Maybe SEMAPV could provide a definition of a "MappingRule" class?

**Comment by matentzn** [comment]
Thank you for your comments @saubin78 - I am in a deadline mode atm, but will get to this soon!

**Comment by matentzn** [comment]
This is still top of my list @saubin78 - sorry about the delay.
