### ISSUE TITLE
Add subject/object qualifier

### ISSUE THREAD

**Issue by cmungall** [mapping-commons/sssom#17]
We want to be able to say things like:

 * uberon:heart = mouse:heart // context= NCBITaxon:10090
 * depth_in_feet = depth // when units = UO:foot

I think it's overloading SSSOM to build in a full post-composition / OWL class expression mechanism, but it would still be useful to have qualifier fields for subject and object that have context-specific reliable interpretations

**Comment by matentzn** [comment]
> context-specific reliable interpretations 

These will have to be manually built in the tools; else how would you generate an "owl reified axiom" from such a mapping; Why not at least introduce a template mechanism like this:

```
object_template: ?SUBJECT RO:0002160 NCBI:10090
``` 
This would tell the parser that (in this case the object, but analogously the subject) should be interpreted as a class expression with the ?SUBJECT (`subject_id`) being the filler. That is more generic, not much more verbose, and covers a wider range of use cases (for example, you could have templates on both sides of the mapping!).

**Comment by matentzn** [comment]
Superseded by #108
