### ISSUE TITLE
Make SSSOM 1.0 release

### ISSUE THREAD

**Issue by matentzn** [mapping-commons/sssom#189]
All features are merged now.

Before we make a formal release we will have to deal with these two:
- [x] https://github.com/mapping-commons/semantic-mapping-vocabulary/issues/2
- [X] https://github.com/mapping-commons/sssom-py/issues/256 (to make sure no problems with toolkit from current standard), cc @hrshdhgd 
- [X] Update all documentation/specification/tutorial pages to reflect these changes DONE: https://github.com/mapping-commons/sssom/pull/205/files
- [x]  Update changelog https://github.com/mapping-commons/sssom/blob/master/CHANGELOG.md

Target date for 1.0 release: June 10.

**Comment by matentzn** [comment]
I added now another intermediate release 0.9.4 which reflects all the changes we wanted to get in for SSSOM 1.0. 
https://github.com/mapping-commons/sssom/releases/tag/0.9.4

I still want to leave at least a window open for the review from @graybeal and @ernestojimenezruiz on the CV above, but I have now updates basically everything to use the vocab as is.

**Comment by saubin78** [comment]
Hi! Do you plan to release the new version of SSSOM soon?

**Comment by matentzn** [comment]
We are still rolling with the 0.9.X series, are you asking because of the curation_rules?

**Comment by matentzn** [comment]
It is top of my list; I will make a new release at the end of next week, is that ok?

**Comment by saubin78** [comment]
Great! Thanks Nico

**Comment by matentzn** [comment]
After 4 years, the day has come.

With 79 contributors writing more than 1200 comments over the last 4 years, we have done it!

https://github.com/mapping-commons/sssom/releases/tag/v1.0.0

## Contribution stats for SSSOM from 2020-04-20 to 2024-08-09

Created with [grainyhead](https://github.com/gouttegd/grainyhead).

| Event | Total | Internal | Internal (%) | External | External (%) |
| -------- | -------- | -------- | -------- | -------- | -------- |
| Contributors | 79 | 21 |  26.58 | 58 |  73.42 |
| Issues opened | 218 | 172 |  78.90 | 46 |  21.10 |
| Issues closed | 114 | 110 |  96.49 | 4 |  3.51 |
| Pull requests opened | 154 | 145 |  94.16 | 9 |  5.84 |
| Pull requests closed | 152 | 146 |  96.05 | 6 |  3.95 |
| Pull requests merged | 129 | 126 |  97.67 | 3 |  2.33 |
| Comments | 1230 | 1017 |  82.68 | 213 |  17.32 |
| Commits | 345 | 328 |  95.07 | 17 |  4.93 |
| Releases | 13 | 13 |  100.00 | 0 |  0.00 |
