### ISSUE TITLE
mapping_tool  

### ISSUE THREAD

**Issue by cmungall** [mapping-commons/SSSOM#20]
From Hyeongsik:

SSSOM currently has mapping_tool fields but it could be a bit more specific similar to the agent information from web browsers, e.g., Mozilla/5.0. We just wanted to make sure that the same alignment results can be precisely reproduced using a specific version of an alignment tool, which could be helpful for testing and benchmarking different alignment tools for the purpose of research. At least, I wish SSSOM would support separate fields or predefined format for program id/name and version fields/build numbers, etc.

**Comment by matentzn** [comment]
We could use [user-agent string syntax](https://harzing.com/resources/publish-or-perish/manual/reference/user-agent-syntax) as you suggest as a standard notation. Or we add `mapping_tool_version`. I am fine with either way!

**Comment by matentzn** [comment]
Closing in favour of #71
