### ISSUE TITLE
Broken links in documentation

### ISSUE THREAD

**Issue by AlasdairGray** [mapping-commons/sssom#215]
The download links for TSV examples, e.g. https://raw.githubusercontent.com/matentzn/SSSOM/master/examples/external/mp-hp-exact-0.0.1.sssom.yml, are broken.

<img width="1283" alt="Screenshot 2022-07-29 at 11 25 17" src="https://user-images.githubusercontent.com/1141265/181739846-433ac5de-887b-4121-92e7-01c2630652a5.png">

**Comment by matentzn** [comment]
Thank you @AlasdairGray, fixed: https://github.com/mapping-commons/sssom/pull/216

Will take a few minutes to show up on the webiste.
