### ISSUE TITLE
Interested to be in the team

### ISSUE THREAD

**Issue by linikujp** [mapping-commons/sssom#22]
Hi All,
I am planning to work with few ontologists on mapping schema for various CDM mapping. I'd like to contribute or coordinate with this group. 
Thanks,
Asiyah

**Comment by matentzn** [comment]
Thats great! yeah, we are open to suggestions of any kind! What exactly are you planning to do? CDM = Common Data Model? Does this mean you are working to map clinical ontologies primarily? Which ones?

**Comment by linikujp** [comment]
Our initial thought is to align some CDM harmonization work done here: https://www.fda.gov/drugs/coronavirus-covid-19-drugs/covid-19-real-world-data-rwd-data-elements-harmonization-project
There are some other works mapping OMOP to OBO, and we'd like to see if there is a process to assess the quality of terminology alignment in some text mining or terminology mapping work. 
We are still in planning phase, and will keep you updated. Please let us know if you have similar thoughts from your group.

**Comment by matentzn** [comment]
Great! I can see a lot of cool work in the CDM area when following your link, but I could not, on first glance, see any concrete thoughts on terminology mapping - I saw the mapping spreadsheet of course, which appears to be mapping data model fields across various CDMs.. I will wait for more concrete thoughts from you, and looking forward to working together :)

**Comment by matentzn** [comment]
I have added you to the team @linikujp

https://github.com/orgs/mapping-commons/teams/sssom-core
