### ISSUE TITLE
[New metadata element]: registry title

### ISSUE THREAD

**Issue by anitacaron** [mapping-commons/sssom#238]
**Element id (e.g. creator_id, mapping_tool_version):**
(Must be lower case and contain only letters and underscores.)

```
registry_title
```

**Value data type (e.g. URI, URL, text, xsd:boolean):**

```
xsd:string
```

**Description**
(Provide a human-readable description that clarifies the intended use of the metadata element.)

Title for the registry.

Example: https://github.com/mapping-commons/mh_mapping_initiative/blob/master/registry.yml

**Comment by matentzn** [comment]
@anitacaron excellent, would you like to give it a shot and make a PR on this file here: https://github.com/mapping-commons/sssom/blob/master/src/sssom_schema/schema/sssom_schema.yaml

**Comment by matentzn** [comment]
This has been fixed in #240
