### ISSUE TITLE
[New metadata element]: registry description

### ISSUE THREAD

**Issue by anitacaron** [mapping-commons/sssom#239]
**Element id (e.g. creator_id, mapping_tool_version):**
(Must be lower case and contain only letters and underscores.)

```
registry_description
```

**Value data type (e.g. URI, URL, text, xsd:boolean):**

```
xsd:string
```

**Description**
(Provide a human-readable description that clarifies the intended use of the metadata element.)

Description of the registry.

Example: https://github.com/mapping-commons/mh_mapping_initiative/blob/master/registry.yml

**Comment by matentzn** [comment]
Excellent, could you add this element yourself in https://github.com/mapping-commons/sssom/blob/master/src/sssom_schema/schema/sssom_schema.yaml

Thank you for this issue!

**Comment by matentzn** [comment]
This has been fixed in #240
