### ISSUE TITLE
Bad Link: usecases.md to MONDO

### ISSUE THREAD

**Issue by croeder** [mapping-commons/sssom#243]
src/docs/usecases.md has a bad link to MONDO's sssom's mappings.
Page with bad link:
https://github.com/mapping-commons/sssom/blob/master/src/docs/usecases.md

address that gives 404:
https://github.com/monarch-initiative/mondo/tree/sssom-rewrite/src/ontology/mappings

**Comment by matentzn** [comment]
Thank you @croeder! Fixed this!
