### ISSUE TITLE
how to use subject_category and object_category?

### ISSUE THREAD

**Issue by saubin78** [mapping-commons/sssom#256]
Hi,
the documentation for both those metadata elements lacks clarity :

> The conceptual category to which the subject belongs to. This can be a string denoting the category or a term from a controlled vocabulary.

what do you mean by category? Is it a semantic one, like "disease", "material", "activity", etc.? If not, what? 
What's their purpose?

**Comment by matentzn** [comment]
@saubin78 Thank you, as always, for your awesome feedback. Can you check if this is making it clearer: https://github.com/mapping-commons/sssom/pull/257

Please be strict, this should really be improved significantly.

**Comment by matentzn** [comment]
@saubin78 did you get a chance to look at #257 ? Is this ok for now?

**Comment by matentzn** [comment]
Fixed an release
