### ISSUE TITLE
Document how to create a new mapping commons using cookiecutter

### ISSUE THREAD

**Issue by matentzn** [mapping-commons/sssom#273]
@hrshdhgd would you be able to add a documentation page here https://github.com/mapping-commons/sssom/tree/master/src/docs called `create-mapping-commons.md` and fill it with some initial instructions and 

1. how to create a new mapping commons from zero to hero and
2. how to update one

We have a new team member (@ehartley) who will help us building the template up.

**Comment by hrshdhgd** [comment]
Do you mean using https://github.com/mapping-commons/mapping-commons-cookiecutter ?

**Comment by matentzn** [comment]
Sorry I meant to share that link! Yes exactly!

**Comment by hrshdhgd** [comment]
Started a stub: https://github.com/mapping-commons/sssom-py/pull/374

I don't know what the end product is supposed to look like.

**Comment by hrshdhgd** [comment]
Completely messed that up. Sorry! https://github.com/mapping-commons/sssom/pull/277
