### ISSUE TITLE
Document the SSSOM release pipeline

### ISSUE THREAD

**Issue by matentzn** [mapping-commons/sssom#288]
We need a complete doc for the whole SSSOM release pipeline, as it is quite complicated right now:

https://docs.google.com/document/d/17Cssk63jhqd17H_PXoIqCNBKcWA-8HyVF9voNFa67v4/edit

**Comment by hrshdhgd** [comment]
Updated the doc. Kindly review.

**Comment by matentzn** [comment]
Excellent @hrshdhgd 

## Final process

1. Finish your edits and merge them into master
2. Rebuild the LinkML model using the [“build” action](https://github.com/mapping-commons/sssom/blob/master/.github/workflows/build.yml)
3. Create a [GitHub release](https://github.com/mapping-commons/sssom/releases)
    - This will automatically trigger a PyPI release using [this action](https://github.com/mapping-commons/sssom/blob/master/.github/workflows/pypi-publish.yaml), of the sssom_schema module
    - The context file is packaged and delivered to projects that depend on `sssom-schema`.
4. Updating sssom-py
    1. After the pypi release is completed,  update sssom-schema dependency using `poetry update sssom-schema`.  The new context is available and accessible via `pkg_resources`.
    1. Release `sssom-py` using the same method as `sssom-schema` above.

Can you put this on a page in the documentation, so I can try it next time?

**Comment by hrshdhgd** [comment]
Where do you think this should go? [`spec.md](https://mapping-commons.github.io/sssom/spec/)` or a separate page?

**Comment by hrshdhgd** [comment]
For now I've created a new `update.md` and added it to the nav bar.
