### ISSUE TITLE
Missing property on web page

### ISSUE THREAD

**Issue by jonquet** [mapping-commons/sssom#293]
Go to : 
https://mapping-commons.github.io/sssom/

publication_date is referred here: 
https://mapping-commons.github.io/sssom/publication_date/

However, the properties is not used by any of the objects described on the page (Mapping, MapppingSet, MappingRegistry, MappingSetReference).

**Comment by matentzn** [comment]
Thank you @jonquet for the report! This will be fixed in #294!
