### ISSUE TITLE
Relationship to PROV-O

### ISSUE THREAD

**Issue by udp** [mapping-commons/sssom#3]
Not for the first version, but it would be interesting to think about how SSSOM relates to PROV-O.  e.g. would mappings have prov:wasGeneratedBy properties?  could ontology alignment be a prov:Activity?

**Comment by Chris-Evelo** [comment]
Yes, looking at how to best capture provenance is important. In the Open PHACTS project, we used VoID for that. You really want to capture more detail like who captures this, using what, from what, when, and using which versions. Typically that will be layered. Like these mappings were created based on the mappings available at that resource, and the resource itself should indicate how they created those.

**Comment by matentzn** [comment]
Some examples from slack convo with @cmungall  `mymappings was-generated-by [a CurationActivity; timestarted...]`

**Comment by matentzn** [comment]
Would someone be able to work on this? I think concretely, it would be nice to at least document how the two relate, perhaps even implement them in sssom-py

**Comment by ddooley** [comment]
I have to review PROV-O from a process ontology development angle.  But to be of help with respect to SSSOM, I'd need to read a 2 pager on what SSSOM goals/capabilities are, down to the entity type - is there such at thing?  Is the question what OBOFoundry entities map to PROV-O, or what data structure PROV-O has that SSSOM needs?

**Comment by mellybelly** [comment]
pls assign (at least one person anyway) to @mbrush

**Comment by ddooley** [comment]
I'll note that my PROV-O review is limited to process related terms, but SOSA is also reviewed in the same light, both with respect to OBO in [this table](https://docs.google.com/spreadsheets/d/1pWqSnlltNk_xXssNqt5o_L6u2i3eq9JXJAgGQNvV6cI).  It reveals mapping cases that it sounds like SSSOM strives to describe.

**Comment by matentzn** [comment]
The task for the workshop is to determine which properties and best practices from PROV should be adopted in SSSOM, and which [SSSOM metadata elements](https://github.com/mapping-commons/sssom-py/blob/master/schema/sssom.yaml) should be mapped to prov: metadata elements. Overall, we need to ensure that we can model mapping provenance in a standard, reliable (yet minimal) way, and we have not missed anything important.

**Comment by cmungall** [comment]
Proposal below. The essence is to allow granularity where people need it, and to keep the sssom tsv simple, with the most useful parts of the prov payload denormalized as sssom fields.

 * Add an optional column was_generated_by, with slot_uri pointing to the prov property
 * The range of this would be a CURIE denoting a (named) instance of a prov activity
 * The CURIE prefix MUST be registered in the header
 * the expanded URL SHOULD resolve, and MAY resolve to both computable and human readable info via conneg
 * the prov activity MAY be included as YAML-LD in the header
 * If a prov activity is provided, it must be consistent with the projected sssom fields
    * mapping_tool = activity.wasAssociatedWith, range SoftwareAgent
    * creator_id = activity.wasAssociatedWith, range Person
    * subj,obj source = activity.used
    * the prov object MAY include wasDerivedFrom between subj/obj sources and the sssom mapping set
    * etc

**Comment by mbrush** [comment]
Hi all.  I don't have a deep understanding of the requirements/use cases related to provenance for SSSOM, but Chris' proposal above sounds reasonable. Cant make the workshop, but happy to follow up later and review any concrete examples/proposals that come out of it.

**Comment by matentzn** [comment]
Other impressions from workshop:
- Look at vocabs like https://github.com/sifrproject/MOD-Ontology/blob/master/mod-v1.4_properties_template.ttl  for properties commonly used
- There are perhaps multiple activities involved here: 
   - mapping creation
   - mapping review
   - mapping reconciliation (activity on mapping set level)
- Define Inputs and outputs of activities?
- (Will add more in a bit)

**Comment by matentzn** [comment]
from @graybeal 

- Check 20-30 provenance related properties that could be relevant: [list](https://hal.archives-ouvertes.fr/lirmm-01605783)
    - list of most-recommended terms as a template: https://github.com/sifrproject/MOD-Ontology/blob/master/mod-v1.4_properties_template.ttl

**Comment by matentzn** [comment]
This is now described in our recent OM 2022 report. The gist: the `mapping_justification` is a PROV:Activity that confirms/generates the Mapping. Agents acting on Mappings include people (author_id) and tools (mapping_tool).
