### ISSUE TITLE
add category information for subjects and objects

### ISSUE THREAD

**Issue by wdduncan** [mapping-commons/SSSOM#32]
In some cases, it is important to know what type of entity the subject and/or object is; e.g., class, property, annotation (perhaps primitive data types too?). Can we columns such as subject_category and object_category to capture this info?

cc @cmungall

**Comment by matentzn** [comment]
`match_term_type` is not enough? 

```

Specifies what type of terms are being matched (class, property, or individual). Value should be ID from Term Match (SSSOM:TermMatch) branch of the SSSSOM Vocabulary.
```

**Comment by matentzn** [comment]
that was a request by @ernestojimenezruiz

**Comment by matentzn** [comment]
(as an aside, `object_category` is already used for [something else](https://github.com/OBOFoundry/SSSOM/blob/master/SSSOM.md#meta))

**Comment by wdduncan** [comment]
Thanks @matentzn   
I think that works. What do you think @cmungall ?

**Comment by matentzn** [comment]
I think this is good enough for now, please reopen if you disagree.
