### ISSUE TITLE
Documentation issue: can’t find any “metadata elements labelled with L”

### ISSUE THREAD

**Issue by gouttegd** [mapping-commons/sssom#322]
[The spec says](https://mapping-commons.github.io/sssom/spec/#tsv) about the TSV format that

> All SSSOM metadata elements labelled with L in the metadata table are permissible as column names in the TSV.

I assume the “metadata table” refers to [this page](https://mapping-commons.github.io/sssom/Mapping/) (there’s a link to it further in the same paragraph). But I can’t find any “L” label in that table. Is there another “metadata table” somewhere else?

**Comment by matentzn** [comment]
This information is from an ancient version of the spec and should be removed. Back then, the spec was a markdown table embedded in that overview document..

**Comment by gouttegd** [comment]
No longer relevant since #368.
