### ISSUE TITLE
The spec/doc should be reorganised

### ISSUE THREAD

**Issue by gouttegd** [mapping-commons/sssom#330]
Right now, the SSSOM website is a bit of a mess.

* The [home page](https://mapping-commons.github.io/sssom/home/) and the [about page](https://mapping-commons.github.io/sssom/about/) are mostly redundant.
* The [specification page](https://mapping-commons.github.io/sssom/) is merely the auto-generated documentation of the underlying LinkML model – calling that a “specification“ is misleading as this is woefully insufficient to anyone willing to implement the standard (necessary, sure, but not sufficient).
* The [overview page](https://mapping-commons.github.io/sssom/spec/) (which, also misleadingly, is under the URL `/sssom/spec/`) is a bit of everything:
  * a list of contributors (nothing wrong with that but maybe could get its own page, or be added to the existing [credits page](https://mapping-commons.github.io/sssom/credits/);
  * a general introduction to the concept of mapping;
  * a fleeting reference to the data model;
  * a list of the commonly used and recommended mapping predicates;
  * an attempt at formally specifying the OWL/RDF and SSSOM/TSV serialisation formats;
  * a list of use cases.
* The “resources for users“ section it itself a mix of many things. Strikingly, it contains bit that really belong to the “specification” part, such as this (in the [basic tutorial](https://mapping-commons.github.io/sssom/tutorial/#curie)):

> All three must be referred to by an identifier in CURIE syntax ([Compact URI](https://www.w3.org/TR/2010/NOTE-curie-20101216/)) when using the SSSOM table format or JSON, or an IRI (Internationalized Resource Identifier) when you are using the RDF representation of SSSOM.

Overall this makes it very difficult for implementers to figure out what and where are the really “normative“ parts of the website. This is of course at least partially due to the fact that the website is clearly a “work in progress“, but also, more fundamentally, because the website somehow tries to be simultaneously a _specification_ for the standard, a _documentation_ of that standard for end-users, a documentation of the reference implementation (`sssom-py`), and an _academic paper_ on semantic mappings.

More immediately, this makes it difficult for me to figure out where I should put the various improvements to the spec I have been thinking about (such as the propagation of metadata slots #305, the recommendations on backwards compatibility #325, or the recommendations on how to deal with non-standard slots #328).

Therefore I’d like to propose that the website be reorganised so as to clearly separate the _specification_, the _documentation_, and the _general notions on mappings_. I welcome any suggestion for a better organisation, but right now here’s what I’m considering:

* About this document (overall purpose of this document)
* Introduction to semantic mappings (mostly, what is currently in the introduction of the [overview](https://mapping-commons.github.io/sssom/spec/#introduction), though I think some of the stuff in the “resources for users“ could probably belong there as well)
* SSSOM specification (everything that developers must know to develop software compatible with the standard)
  * Introduction and use cases (what the standard is and what it is for)
  * Specification of the data model
    * Auto-generated LinkML-derived documentation
    * Complements to the auto-generated documentation (anything that is not described in the schema but that are necessary to understand the data model)
  * Specification of the serialisation formats
    * OWL/RDF serialisation
    * SSSOM/TSV serialisation
    * JSON serialisation
* User documentation (most of the “resources for users“ stuff)
* Other stuff (credits, glossary, how to contribute, etc.)

Thoughts?

**Comment by matentzn** [comment]
I 100% agree with all you propose. I would love to try and implement (at least in spirit) a version of https://diataxis.fr/, but your proposal is mostly reorganisation at a higher level.

**Comment by gouttegd** [comment]
A first round of reorganisation was done in #368, but the user-facing doc (“resources for users”) still probably needs a bit of love.

**Comment by matentzn** [comment]
Do you want to meet for 1 hour of your choice to hack at that together? I am fine to do it, but maybe could avoid some back and forth if we do it face2face.

**Comment by gouttegd** [comment]
User-facing documentation is not really my priority for now – I’d rather put the spec in shape for a 1.0 version. Was actually thinking of opening an issue to discuss that (basically the question is: what is still needed before we can call the current state a “1.0” version?), but happy to discuss that e.g. in tomorrow’s “OBO tech support call” (wouldn’t be the first time we hijack it to talk about SSSOM).

**Comment by matentzn** [comment]
Ok perfect!

**Comment by matentzn** [comment]
@gouttegd this is assigned to you, if you want me to handle subitems of this task, let me know. (this item is on milestone 1.0, and I am not too sure of Definition of Done (DoD), and my role in it)

**Comment by gouttegd** [comment]
What was important for 1.0 was to reorganize the _spec_, which has been done as part of #368.

I have little interest in the user-facing _doc_, and I think you already reorganized it enough as part of #377.
