### ISSUE TITLE
In SSSOM draft the link to 'SSSOM schema' is broken

### ISSUE THREAD

**Issue by paulacalipho** [mapping-commons/sssom#340]
In https://mapping-commons.github.io/sssom/spec/#minimum the link-out to [SSSOM schema](https://github.com/mapping-commons/sssom/blob/master/model/schema/sssom.yaml) is broken.
Many thanks

**Comment by matentzn** [comment]
Thank you @paulacalipho https://github.com/mapping-commons/sssom/pull/341
