### ISSUE TITLE
How to order repeated slots in TSV 

### ISSUE THREAD

**Issue by dr-shorthair** [mapping-commons/sssom#343]
The [ordering of columns in the SSSOM TSV representation](https://mapping-commons.github.io/sssom/spec/#tsv) is expected to follow [the sequence of elements in the Mapping specification](https://mapping-commons.github.io/sssom/Mapping/#slots). 

1. How is this managed for those slots that may be repeated (e.g. author, reviewer)? 
- repeated columns?
- multiple values in one column?

2. And how to manage it where the slots come in logical pairs, e.g. author_id, author_label? 
They should be coupled or interleaved somehow.

**Comment by matentzn** [comment]
Thank you for your question @dr-shorthair!

> How is this managed for those slots that may be repeated (e.g. author, reviewer)?

multiple values in one column, pipe-separated. See a larger example here: https://github.com/mapping-commons/mh_mapping_initiative/blob/master/mappings/mp_hp_mgi_all.sssom.tsv

> And how to manage it where the slots come in logical pairs, e.g. author_id, author_label?
They should be coupled or interleaved somehow.

See #344
