### ISSUE TITLE
Distinguish candidate mappings and validated mappings

### ISSUE THREAD

**Issue by huanyu-li** [mapping-commons/sssom#350]
Hi,

I'd like to ask how SSSOM distinguish candidate mappings and validated mappings.
For instance, I have candidate mappings generated by some tool like LogMap based on some lexical matching techniques.
Further the mappings are reviewed by a domain experts. Is there a way for SSSOM to include all such provenance information (tool, justification of lexical matching, justification of manual checking, reviewer)?

Thanks!
Best,
Huanyu

**Comment by matentzn** [comment]
Hello @huanyu-li - thank you for reaching out! We just had a long discussion about this, with people asking for it and people pushing back:

https://github.com/mapping-commons/sssom/issues/345

Feel free to offer your opinion! I will close this issue here to redirect all traffic to the same place.

**Comment by huanyu-li** [comment]
Thank you so much, Nico!
