### ISSUE TITLE
[repo hygeine] Move everything mkdocs related to a dev dependency

### ISSUE THREAD

**Issue by cmungall** [mapping-commons/sssom#354]
Continuing from

- #353 

In fact the version of mkdocs or any mkdocs plugin should be of zero concern to any consumer of sssom

The plugin is erroneously in the main dependencies:

https://github.com/mapping-commons/sssom/blob/2677726a1702ab6a556f9a9dc1040e58ed37489d/pyproject.toml#L12-L19

**Comment by matentzn** [comment]
@hrshdhgd can you do this in a calm minute?

**Comment by hrshdhgd** [comment]
Great catch Nico. I should have waited to approve the PR... sorry. Fixing it right now.
