### ISSUE TITLE
Define canonical sort order

### ISSUE THREAD

**Issue by cmungall** [mapping-commons/sssom#39]
For diff purposes

Suggested: alphanumeric order prioritized by either (1) default column ordering or (2) default column ordering but all ID fields first (to avoid spurious diffs if labels change)

(we will likely want a diff function in sssom-py, but we also want to maximize value of git diffs)

**Comment by matentzn** [comment]
This had been solved, see #247 for details.

**Comment by matentzn** [comment]
- [ ] Document canonical sort order in docs

**Comment by gouttegd** [comment]
This _is_ documented already: https://mapping-commons.github.io/sssom/dev/spec-formats-tsv/#canonical-sssomtsv-format

> a canonical SSSOM/TSV writer:
> […]
> * MUST serialise the slots in the order they appear in the [“Slots” table](https://mapping-commons.github.io/sssom/dev/MappingSet/#slots), in the documentation for the MappingSet class;
> […]
> * MUST write the columns in the order the slots appear in the [“Slots” table](https://mapping-commons.github.io/sssom/dev/Mapping/#slots), in the documentation for the Mapping class;
> […]
> * MUST sort the mappings in lexicographical order on all their slots, in the order the slots appear in the [“Slots” table](https://mapping-commons.github.io/sssom/dev/Mapping/#slots).
