### ISSUE TITLE
Need to have metadata fields for the data model location of terms/code in both subject (source) and object (target)

### ISSUE THREAD

**Issue by jiaola** [mapping-commons/sssom#44]
In CCDH, we're trying to create a mapping from the NCI nodes' data dictionaries to NCIt codes that will be used in the common model. For example, in NCI GDC (genomic data commons) data model Aliquot, and attribute analyte_type,  "cfDNA" is a value in the enum of terms for the attribute. The attribute will be mapped to Specimen.analyte_type in the common data model (CDM). At the same time, the term 'cfDNA' is going to be mapped to NCIT:C128274. We need to record the field mapping (GDC.Aliquot.analyte_type -> CDM.Specimen.analyte_type) in the term mapping to provide context and also reference. 

We were trying to use SSSOM:subject_match_field and SSSOM:object_match_field for this purpose but that seems to be incorrect. What metadata fields should we use?

**Comment by nicolevasilevsky** [comment]
https://terminology.ccdh.io/docs#/CRDC-H%20and%20CRDC%20Node%20Models/get_model_entity_attribute_mappings

**Comment by matentzn** [comment]
Is this issue covered by #43 (despite the slightly wrong title)?

**Comment by matentzn** [comment]
Closing in favour of https://github.com/mapping-commons/sssom/issues/43
