### ISSUE TITLE
broadMatch and narrowMatch may have been reversed

### ISSUE THREAD

**Issue by hsolbrig** [mapping-commons/SSSOM#46]
Referring to the [SKOS spec](https://www.w3.org/TR/2009/REC-skos-reference-20090818/#semantic-relations):

“A triple `<A>` skos:broader `<B>` asserts that `<B>`, the object of the triple, is a broader concept than `<A>`” 

skos:broadMatch is a sub-property of skos:broader 

As I read this,   `<X>` skos:broadMatch `<Y>` says that **`<Y>`** is broader than **`<X>`**.  The current documentation appears to say exactly the opposite?

**Comment by matentzn** [comment]
@hsolbrig wow absolutely.. Thank you! I will fix this asap.
