### ISSUE TITLE
Constraints on TSV comments

### ISSUE THREAD

**Issue by balhoff** [mapping-commons/SSSOM#54]
Is it the case that no comment lines can appear once the TSV starts? Meaning, the comments must be in a contiguous block at the start of the file? This would make sense to me. 

Also, is it the case that any comments must constitute valid YAML syntax after stripping the leading `#`? That's the impression I get from the spec, but I think it could be stated more directly.

**Comment by matentzn** [comment]
You are absolutely right! I will add it to the specs.
