### ISSUE TITLE
best practice for mapping two measurement concepts that take different units

### ISSUE THREAD

**Issue by cmungall** [mapping-commons/SSSOM#56]
Example 1:

 subject = "s:depth"
 object = "o:depth"

conceptually these are the same, but subject is for a property whose range is a literal with implicit unit of meters and object is for a property whose range is a literal with implicit unit of cm

Example 2:

 subject = "s:depth_in_meters"
 object = "o:depth"

conceptually these are the same, but subject is for a property whose range is a literal with unit of meters and object is for a property whose range is a string conforming to "{number} {unit}" syntax

I would say in both cases it is incorrect to use skos:exactMatch because the CURIE pairs denote different concepts, although the CURIEs are *about* the same concept. So we would instead go to skos:closeMatch. This is not wrong, however, it seems unsatisfactory as the concepts are "conceptually closer" than other close matches

Proposed recommendation:

 * skos:closeMatch is not wrong
 * define a new predicate `is_about_identical_concepts`. Formally: `S is_about sc, O is_about oc, sc exactMatch oc`.
 * add a new column intended for the unit case

cc @wdduncan @pbuttigieg

**Comment by wdduncan** [comment]
I agree that that there is a difference that needs to be represented, but from what I've read about `skos:exactMatch` ([here](https://www.w3.org/TR/skos-reference/#L4858)), `skos:exactMatch` links between concepts. So, `depth` (with an implicit unit of meter) can be a `skos:exactMatch` to `depth_in_meters`.  As an aside, if the implicit unit for `depth` was centimeters, then I suppose `skos:relatedMatch` would work.

If we need to capture the syntactic (or representational) dimension, how about using predicates such as `syntaxExactMatch`, `syntaxCloseMatch`, etc.?

**Comment by mellybelly** [comment]
@rmoffitt or @DaveraGabriel may have good examples for how unit reconciliation is captured algorithmically for transformations

**Comment by matentzn** [comment]
Closing in favour of #61
