### ISSUE TITLE
Embedded mode format discussion

### ISSUE THREAD

**Issue by matentzn** [mapping-commons/SSSOM#6]
@cmungall: "Embedded mode: can we make it yaml with an implicit @context?"

**Comment by matentzn** [comment]
I think we should at least use the same format for the metadata in embedded and external mode; you want them both in yaml?

By implicit you mean: the spec assumes that for any sssom mapping file, we use the context provided here?

**Comment by matentzn** [comment]
Like that?

https://github.com/matentzn/SSSOM/pull/8/files

**Comment by cmungall** [comment]
> I think we should at least use the same format for the metadata in embedded and external mode; you want them both in yaml?

I'm inclined to this so long as there is a well-defined transform between the two it's OK to be different. But we should poll others

**Comment by matentzn** [comment]
Ok I personally think that whatever solution, it should be uniform; So I switched it to yaml now. So the mappings set metadata is always represented in yaml, and their is an implicit connection to a JSON LD context for the SSSOM vacabulary.

**Comment by matentzn** [comment]
This has been finished - embedded mode is now the default.
