### ISSUE TITLE
License for using SSSOM

### ISSUE THREAD

**Issue by matentzn** [mapping-commons/sssom#64]
Any suggestion what to use for a license for SSSOM? I am all for public domain, but wanted to check for opinions first.

**Comment by wdduncan** [comment]
I'm fine CC0 or CC-BY. Preferably the former.

**Comment by matentzn** [comment]
One suggestion would be to use

- CC0 for the data model/schema
- BSD for sssom-py (we use it everywhere else across OBO)

We should also make a very glass clear encouragement to publish the individual mappings as cc0, but that is sort of orthogonal

**Comment by mellybelly** [comment]
+1 CC0 for SSSOM, prefer CC-BY 4.0 for mappings to encourage provenance maintenance.

**Comment by nlharris** [comment]
I'm not sure how much merit this has, but a user just complained about CC0 not being a recommended license for software (which I realize you're not suggesting it for). They wanted biolink to use Apache 2.0. https://github.com/biolink/biolink-model/issues/920

**Comment by matentzn** [comment]
At first, I wanted to argue against this, but I see now that @noelmcloughlin has a point that I was never aware of. This Stackexchange question explains it well.

https://opensource.stackexchange.com/questions/133/how-could-using-code-released-under-cc0-infringe-on-the-authors-patents

Thank you for sharing @nlharris that is very important feedback. @kltm could you provide us with some recommendations that would be applicable to all software projects around Monarch? 

@jamesaoverton may also be interested (he probably knew this)

**Comment by kltm** [comment]
@matentzn From the same issue you reference (https://github.com/biolink/biolink-model/issues/920#issuecomment-975818815), depending on exactly what effect you want, I think the choices would likely be a BSD 3-clause license or Apache 2.0. I believe it's better to use a well-understood _software_ license no matter what. The idea is to find the license that most correctly and *clearly* expresses your desired future relationship with downstream users, re-users, etc. Issues like warranty, liability, endorsement, patents, and so on are best expressed explicitly, rather than hoping for the best--there are the issues that can create problems and you want to have done the best for yourselves and your institution.

**Comment by kltm** [comment]
For a direct recommendation, I'd probably want a bit more information. The summary would be BSD 3-clause is simplest and Apache 2.0 is "safest", with many more things spelled out explicitly, like contributions, trademark, patents, and so on.

**Comment by matentzn** [comment]
Thank you.. I guess there are three things:

1. The associated tooling (based on what you say, I would suggest BSD-3, but I don't really mind)
2. The data model/standard: CC-0 (is this appropriate? should this fall under "software"? seem W3C says ["software licenses apply"](https://www.w3.org/Consortium/Legal/2015/copyright-software-and-document) on standards like OWL.
3. (The recommended license for data represented in the standard, which is converging to CC-BY 4.0 - not that relevant here)

**Comment by kltm** [comment]
@matentzn Much

1) For software tools, BSD 3-clause is a very easy permissive license to work with; it doesn't have all of the features of Apache 2.0, but for most of the scientific/academic work that I've seen, as there are already other community and institutional expectations in play, it has been enough.
2) Hm. I'd generally avoid CC0 in cases where it was not explicitly creative work or "data", but this might well be a "creative work". The W3C license there looks like a BSD license with some IP and change notice modifications (I am not a lawyer). Again, the question is: what do you want and how can you explicitly and clearly communicate it? I don't know much about licensing of standards, except in a few cases where is has gone completely off the rails. Out of curiosity, if you are hoping to treat it like a body of text that can be shared and modified by others, would CC BY 4.0 not give you a little extra coverage? <br> I think part of the question here would be how are you looking at the standard: as a work or as a mechanism?
3) CC BY 4.0 is a solid license, with the only wrinkle being projects like wikidata.

**Comment by graybeal** [comment]
We use BSD 3-clause for our software at Stanford BMIR and haven't heard any complaints or concerns. 

I would prefer the standard not have a formal license (see following for the reason), but if you wanted to give it one I'd go with BSD 3-clause again, for simplicity. 

With respect to data, there are some with credibility who feel that the best license is just a declaration that the data is made publicly available for any use—that as soon as there is an actual license involved, a lawyer must be engaged to interpret the license. (And if you are trying to use data from lots of sources, the mix of licenses makes it all but impossible to be confident of legally reusing the combined data.)   I think it goes beyond your scope to recommend a license for created data, but if you want to I won't object. 

I consider the lines between mappings as data, mappings as standard, and mappings as code to be quite ill-defined.

**Comment by matentzn** [comment]
After some deliberation, descided for going for BSD 3 clause.
