### ISSUE TITLE
External mode format for TSV

### ISSUE THREAD

**Issue by matentzn** [mapping-commons/sssom#7]
@cmungall: "External mode: seems if we are going external, just go external, this is hard to work with on production side: https://github.com/matentzn/SSSOM/blob/master/examples/external/mp-hp-exact-0.0.1.tsv"

I think there is some concern that the connection between the tsv and its metadata can get lost. Would it be a compromise to do as you say and require the mapping to be shipped as a gzipped file containing both the mappings and the metadata?

**Comment by cmungall** [comment]
> Would it be a compromise to do as you say and require the mapping to be shipped as a gzipped file containing both the mappings and the metadata?

hmm, it's convenient to have the URL resolve to an untgzd file. OK, I think my objection is mostly focused on GH rendering which is a poor reason, so I perhaps retract it

**Comment by matentzn** [comment]
I have already resolved to use naming conventions instead of of gzip, see spec. It just bugs me a bit that there is not explicit connections between the two.. Lets see over time what others think.

**Comment by matentzn** [comment]
My proposal for now is that we request that for "external" mode, you should use https://github.com/mapping-commons/SSSOM/issues/73

**Comment by matentzn** [comment]
This has been possible for a long time now, see TSV spec.
