### ISSUE TITLE
Representing literal values in SSSOM

### ISSUE THREAD

**Issue by matentzn** [mapping-commons/sssom#81]
While SSSOM is clearly focused on mappings between controlled vocabulary terms (ids which correspond to some entity in the world), there is a huge amount of work going on that is concerned with "literal" mappings -> mapping a string to a concept in an ontology/controlled vocabulary. These are byproducts for example of pipelines for named entity recognition tasks, or manual mapping efforts of curators that read papers and map strings they read to an ontology concept. I believe that the same concerns that we have for normal terminological mappings also apply here - (provenance, curation rules metadata), and therefore propose to develop a scheme by which we can represent literals in the `subject_id` field. One example would be to use URL encoded strings in a standard namespace:

```
SSSOM_LITERAL:Antinukle%C3%A4re%20Antik%C3%B6rper%20%28Kernantik%C3%B6rper%29
```

I believe this would take care of quite a few problems, and users can easily handle or ignore these kinds of subjects. Note that strictly speaking, this is already permitted by the spec of SSSOM - so we are not discussing here whether this should be allowed or not. The question is more a matter of discussing whether we should as a community recommend a "standard" way to handle literals.

I invite everyone to voice their support, ideas or concerns here.

see related: https://github.com/mapping-commons/sssom-py/issues/28 (@cmungall also has some big plans to use these for mapping reconciliation).

**Comment by cmungall** [comment]
Agree with all the above

 1. The subject_id MUST be a valid CURIE
 2. the CURIE prefix MUST be declared in the header to supplementary metadata file
 3. the CURIE prefix SHOULD be registered on bioregistry.io
     - corollary: no `SSSOM_LITERAL`
 4. the CURIE SHOULD NOT inject IDs into someone else vocabulary/database (except for below)
 5. we will create a new prefix that is intended for CURIEs-for-strings, e.g. sssom.literal
 6. anyone MAY inject into sssom.literal, but if they do they MUST use agreed upon literal to curie translation
 7. a standard literal to CURIE translation SHOULD be used. Candidates:
      - md5 hash
      - urlencode (I favor this)
 8. Different communities MAY create their own extension standards that provide consistent and potentially stricter guidelines than these

An example of an extension would be one for users of LinkML. LinkML allows for the specification of enums, the values of which may be associated with CURIEs within a LinkML schema. To expose these as SSSOM there would be a deterministic mapping that would create a CURIE that has the schema CURIE/URL as base, suffixed with the URL encoding. https://github.com/linkml/linkml/issues/272
