### ISSUE TITLE
Clarify the use of the `Entity` element in the metadata model

### ISSUE THREAD

**Issue by matentzn** [mapping-commons/sssom#84]
There is currently a concept `Entity` in the metadata model that is a bit confusing, not not really used anywhere as far as I know:

https://hrshdhgd.github.io/sssom/Entity/

Do we really need that? @cmungall 

I think attaching `subject_label` etc conceptually to the mapping concept should be sufficient?

**Comment by cmungall** [comment]
I think this is resolved
