### ISSUE TITLE
[New metadata element]: mapping_justification

### ISSUE THREAD

**Issue by NuriaQueralt** [mapping-commons/sssom#85]
**Element id (e.g. creator_id, mapping_tool_version):**
(Must be lower case and contain only letters and underscores.)

```
mapping_justification
```

**Value data type (e.g. URI, URL, text, xsd:boolean):**

```
URI
```

**Description**
(Provide a human-readable description that clarifies the intended use of the metadata element.)

The reason why the mapping claims these concepts are equivalent. These justification claims include saying that the datasets are conceptually about the same type of concept, that they match in their chemical structure, or that they represent the protein generated by some gene. Examples: A linkset between two chemicals that share the same chemical structure would use the value http://semanticscience.org/resource/CHEMINF_000059. A linkset between two proteins would say that they were conceptually the same protein using the value http://semanticscience.org/resource/SIO_010043. A linkset between a protein and a gene would say that they are conceptually the same by stating that it is a protein coding gene with http://semanticscience.org/resource/SIO_000985.

**Comment by NuriaQueralt** [comment]
This predicate was used in the Open PHACTS project. Specifically, it was used the Object Property <http://vocabularies.bridgedb.org/ops#linksetJustification> and the URI values listed in "B.2 Link Justification Vocabulary Terms" section in this doc: http://www.openphacts.org/specs/2013/WD-datadesc-20130912/#appendix-link-justifications

**Comment by NuriaQueralt** [comment]
There is also the 'curation_justification' predicate option that could be merged here. I am not sure whether to merge it, add it as a new predicate or not to add it at all. I made this proposal based on my experience as a curator and also the provenance I saw tracked by text mining systems. One may one to keep the exact 'text sentence' read in the publication (primary source of evidence) where the mapping decision was based on. I envisioned this first as a Data property to link to the text sentence, extracted by the curator or a text mining system. Pros: it is useful for humans. Cons: It is not best practices because it is not machine readable.

**Comment by matentzn** [comment]
Computable justifications are a good idea, but I am unclear what the difference is between a mapping justification and a curation rule #57 ? @NuriaQueralt could you write down from your perspective what the difference is?

**Comment by AlasdairGray** [comment]
@matentzn They are closely related and it depends on your scope of curation rule. If curation rules can be functions, then the justification would be the application of the rule in a specific instance with details of the parameters that were used.

**Comment by matentzn** [comment]
Thank you @AlasdairGray

**Comment by matentzn** [comment]
Superced by #150.
