### ISSUE TITLE
SSSOM needs a logo!

### ISSUE THREAD

**Issue by cthoyt** [mapping-commons/sssom#88]
Slytherin references suggested

➡️ 🐍 ⬅️

**Comment by matentzn** [comment]
haha yeah, we have @jmcmurry for this. Mappings and snakes combined would be gold for a logo!

**Comment by matentzn** [comment]
I think Julies logos have made more of a difference on our professional appearance than any content we have developed :D

**Comment by cthoyt** [comment]
the hype is real... good typography and iconography goes further than anything else. Haven't you ever read a paper in nature that's total BS but looks _amazing_?

**Comment by callahantiff** [comment]
> haha yeah, we have @jmcmurry for this. Mappings and snakes combined would be gold for a logo!

What about a big snake squeezing all of the mappings. It sets the stage nicely for some sssssweet slogans 😉 😜

**Comment by cthoyt** [comment]
![It's snake time](https://64.media.tumblr.com/9e7c98c6b761eb9f9ce3b23c1103c5c0/71b209d595d45613-d2/s1280x1920/5331caa63f7c816e57db293a8fffb460ca9ebabe.png)

**Comment by callahantiff** [comment]
Mapping Noodle??

![image](https://user-images.githubusercontent.com/8030363/134360209-e42ade8b-8bca-49cb-a62f-7249eb141d34.png)

**Comment by cthoyt** [comment]
Danger noodle is easily my favorite snake meme

**Comment by jmcmurry** [comment]
Oh no apologies needed; I have the danger noodle t-shirt. And now you can too! 
https://6dollarshirts.com

**Comment by callahantiff** [comment]
Yep, that needs to happen!

**Comment by jmcmurry** [comment]
ok so I've tried to honor the differences of opinion between snake theme and mapping theme. Each option is a little of both. 1 is visually cleanest and most "S" like, but in 2 & 3 the snake head is a map pin. In 3, conceptually this is 3 origins, one destination (it is also 3 S's if less obviously so).

![image](https://user-images.githubusercontent.com/3658863/141656745-4766c521-0e7a-4118-896d-d6c2431e6acd.png)

PS this is the last time y'all get to name stuff :)

**Comment by matentzn** [comment]
Awesome Julie!!!

**Comment by mellybelly** [comment]
I like no 2 without the snake tongue, but maybe making the snake body look more like the three-part version on the right but the shape in 2? Alternatively no 3 but with a wider border?

Love them all though :-)

**Comment by matentzn** [comment]
I like the three lines on the body: n:1 mapping cardinality. It makes the mapping theme clearer.

**Comment by jmcmurry** [comment]
Here are flavors of the option Melissa was suggesting. Cardinality concept is less obvious, but it is visually cleaner. I can clean up whichever version gets the final consensus.

![image](https://user-images.githubusercontent.com/3658863/141694593-a79c5cd2-ee65-4d0b-a93c-04570f76dcee.png)

B.1 ❤️ 
B.2 🚀 
B.3 👍
B.4 👀

**Comment by joeflack4** [comment]
I might like the B and C in the OP more, but I prefer the "S" to be right-side up, personally.

**Comment by jmcmurry** [comment]
The reason it is rotated is because if the snake head is going to be a map pin, it will only be recognizable if it is oriented normally. The "S" is the least essential concept to take home here. ;)

**Comment by matentzn** [comment]
Ok seems more people are B2 than C.. it's a bit surprising to me because in C you can recognise the lines as mapping lines, while in B2 they look more like a street shaped like the monarch logo.. let's get some more opinions!

**Comment by bpeters42** [comment]
Throwing an alternative out there, and hope my complete lack of graphic design skills don't kill this from scratch. Three separate 'S' shapes merging into one final 'location' symbol. To give 3 mappings, and also the SSS. 4 versions in the below, playing with 2 different angles and with or without starting locations / snake heads. 

![SSS](https://user-images.githubusercontent.com/13860130/141801664-51d38dea-7556-4b8a-b841-c4e8c97c8551.png)

And one more with (gasp) color
![SSS2](https://user-images.githubusercontent.com/13860130/141802977-15b75603-3b60-44ba-b33e-62588ee5bdde.png)

**Comment by matentzn** [comment]
Creative @bpeters42 :P This looks like a mixture of hydra and medusas head to me rather than a snake, and if its hydra, it would carry the sentiment: where you chop one off, two more will grow - nightmare for our mapping scenario. If its medusa, it would be: you look at them and you freeze to stone, which is true in many unfortunate way, but exactly what we want to avoid. (I am only half serious) 

Alright, Friday is voting close. Looks like its a race between

![image](https://user-images.githubusercontent.com/7070631/141977187-4ab8d508-1c9e-43e0-a6ca-8b589d47f6bf.png)

 and

![image](https://user-images.githubusercontent.com/7070631/141977235-c158ef08-50b3-492b-ab10-5c32ac5b8c96.png)


Keep voting until Friday, 19th December, and then the logo will become official! Thank you all!

**Comment by nicolevasilevsky** [comment]
@matentzn do you mean Friday, Nov 19th?

**Comment by graybeal** [comment]
I am sorry to check in so late to this discussion. I have hesitated because, though the logo is very nicely done, I have a fairly strong visceral reaction to it, even if I'm not able to say exactly why. I think if I summarize it as "how do you think people respond emotionally to seeing the head of a snake?", you may get some sense of how it makes me feel. (Perhaps that's why you do not see the snake theme in many logos…)  Anyway, if everyone is on board it's quite possible that I'm a distant outlier, and in context no one will have that reaction. Just wanted to give you a heads up…

**Comment by matentzn** [comment]
@graybeal do you have this feeling equally for all the presented solutions? I think we agreed the snake was a symbol for the ssssssss part of the acrononym, and the "slytherin" nick name.

**Comment by graybeal** [comment]
Yes, they are all snakes with heads, so the fundamental effect is similar. I'm not disagreeing with anything said in this ticket, just noting the way it might feel for some (few?). 

If the snake head were changed to a simple dot, rather than the push-pin/snake-head icon with centered dot, would that be something snaky enough that everyone still liked it? And/or, if we can make the path actually look like an upright S, then the 3 lines would be SSS and maybe it would feel a bit less, umm, wicked?

**Comment by matentzn** [comment]
Alright, I suggest we put off the logo for the new year - unfortunately @jmcmurry wont be able to to anything much for a while, and this issue (which is widely spread - a mild degree of snake phobia - thanks for bringing that to our attention) does go against the very thing we stand for - openness, inclusivity and accessibility (we just didn't think of it). I suggest we stop the vote right now and stay without a logo until we can find one that is more abstracted from the snake representation.

**Comment by cmungall** [comment]
perhaps we should have something that communicates the mathematical concept of mapping more, e.g from https://en.wikipedia.org/wiki/Map_(mathematics)

![wikipedia mapping](https://upload.wikimedia.org/wikipedia/commons/thumb/d/df/Function_color_example_3.svg/440px-Function_color_example_3.svg.png)

Maybe a hyperabstracted version of 

![img](http://eil.stanford.edu/supply_chain/case/mapping_example.JPG)

Perhaps some inspiration can be drawn from the OxO circos:

![image](https://user-images.githubusercontent.com/50745/152025662-919b4f78-c9c0-4da8-b99e-a93e5ee1cb30.png)

**Comment by jmcmurry** [comment]
<img width="403" alt="image" src="https://user-images.githubusercontent.com/3658863/165665221-89f994a5-b2ae-4cc5-8f94-6668209ae7db.png">

**Comment by matentzn** [comment]
I love it. Thank you @jmcmurry for your work on this! Anyone else?

**Comment by cmungall** [comment]
Love it!

**Comment by udp** [comment]
I love this!

Only comment is that it may be good to have a version with the “SSSOM” text bigger and centred in the icon, just for readability’s sake when this is printed small? I’m thinking when this is used in a presentation with other icons the part that says sssom may disappear into the line.

**Comment by joeflack4** [comment]
I was hoping we could work in some way to have a snake in there somewhere, what with it being written in Python and being SSSSSSS-OM, after all. But this new logo looks the best so far!

**Comment by matentzn** [comment]
Done! Thank you so much @jmcmurry

**Comment by joeflack4** [comment]
@matentzn Had some fun with Dall-E and tried seeing what it would generate for this. Couldn't quite get it to do what I wanted, but here are some examples:

![DALL·E 2022-08-19 16 25 29 - black and white logo of a mathematical graph of nodes and edges inside of a circle  each edge in the graph looks like a snake](https://user-images.githubusercontent.com/13045020/185701723-f678820c-f76c-4d47-b711-c281ec661d92.png)

![DALL·E 2022-08-19 16 25 30 - black and white logo of a mathematical graph of nodes and edges  each edge in the graph looks like a snake](https://user-images.githubusercontent.com/13045020/185701728-d251c853-afb4-4ad3-b088-8010b19046b7.png)

![DALL·E 2022-08-19 16 25 31 - black and white logo of a network of nodes and edges  the edges looks like snakes](https://user-images.githubusercontent.com/13045020/185701732-daf750ca-f984-42f9-bc65-13499b21e298.png)

**Comment by matentzn** [comment]
Haha funny. :) Logo choice is done though and we are getting away from the snake thing in favour of a different pronunciation (sesame).. will tell you in a meeting if you are interested
