### ISSUE TITLE
Create user facing SSSOM tutorial

### ISSUE THREAD

**Issue by matentzn** [mapping-commons/sssom#93]
- step-by-step tutorials for the people who have some knowledge on the Semantic Web or KRR so that they can also learn and use these tools
- covering how to build up good terminological mapping sets and how to integrate them into a data workflow (pipeline)
- which use cases are addressed how

**Comment by callahantiff** [comment]
I'd be interested in helping make these if you are looking for volunteers!

**Comment by matentzn** [comment]
That would be really great :) Thanks! I am currently doing my last review of the spec after this I would prioritise the paper and use facing docs. Is there anything in this space you like doing in particular?

**Comment by matentzn** [comment]
I love it, thanks! Maybe we should have a few mapping meeting to get things started to discuss these things? Not only focused on SSSOM, but generally how to do mappings better and promote better practices, which will then automatically lead to creating a list of related tutorials as well. If you are up for it (and anyone else) let me know!

**Comment by callahantiff** [comment]
Sounds really great to me! I'm definitely up for it!

**Comment by matentzn** [comment]
I have now created a draft tutorial here which we will gradually expand: https://mapping-commons.github.io/sssom/tutorial/
