### ISSUE TITLE
Auto-deploy docs when sssom.yaml is changed

### ISSUE THREAD

**Issue by matentzn** [mapping-commons/sssom#95]
see https://github.com/mapping-commons/sssom/commit/4c8e1d39b4b00bce3606b51d1116370fdd8b07ef#commitcomment-57132012

we should be able to have a GH actions autodeploying the docs when sssom.yaml is changed on master

**Comment by cthoyt** [comment]
What's the command to build the docs? I can make the workflow for it

**Comment by matentzn** [comment]
It's literally "make".
